# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hdezier <hdezier@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/06/25 18:08:21 by hdezier           #+#    #+#              #
#    Updated: 2016/06/25 18:10:04 by hdezier          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
#RULES
all :
	make -C nm
	make -C otool

clean :
	make clean -C nm
	make clean -C otool

fclean :
	make fclean -C nm
	make fclean -C otool

re :
	make re -C nm
	make re -C otool

.PHONY: all clean fclean re
