#!/bin/zsh

make

for f in $@; 
do
	echo "\033[33mTest for file: \033[4m$f\033[0m"
	echo "\033[32mTest nm\033[0m"
	diff -sB <( ./ft_nm $f ) <( nm $f )
	if [ $? -ne 0 ];
	then
		echo "error encountred"
		exit 1
	fi
	echo "\033[32mTest otool\033[0m"
#	diff -sB <(./ft_otool $f) <(otool -t $f)
#	if [ $? -ne 0 ];
#	then
#		echo "error encountred"
#		exit 1
#	fi
	echo ""
done
